import { Role } from "@prisma/client";
import { prisma } from "../lib/prisma";

// ===========================================================================
// Real alumni data sourced from:
// - Asutosh Panda: BSC Certificate (2017-2020 batch)
// - Sujit Kumar Gouda: Provisional Certificate (2020-2023 batch)
// - 2023-2026 batch: Final Year Project Status Excel sheet
//
// Fields not available from documents use realistic placeholder values.
// ===========================================================================

const alumni = [
  // ── Past Alumni (already graduated) ──────────────────────────────────────
  {
    name: "Asutosh Panda",
    email: "asutosh.pda@gmail.com",
    year: "2020",
    major: "Computer Science",
    cgpa: 9.4,
    grade: "O",
    company: "Freelance",
    location: "Berhampur, Odisha",
    phone: "+91 9876500001",
    bio: "BSc CS Honours graduate from Saraswati Degree Vidya Mandira, Berhampur University. Passionate about full-stack development and open source.",
    skills: ["JavaScript", "React", "Node.js", "Python", "Docker"],
    linkedinUrl: "https://www.linkedin.com/in/asutoshpanda",
    githubUrl: "https://github.com/asutoshpanda",
    portfolioUrl: "https://asutosh.dev",
    resumeUrl: "https://drive.google.com/file/d/asutosh-resume",
    projectName: "Alumni Management Portal",
    projectUrl: "https://alumni-portal.onrender.com",
    placementInfo: "Freelance Software Engineer",
  },
  {
    name: "Sujit Kumar Gouda",
    email: "sujit.gda997@gmail.com",
    year: "2023",
    major: "Computer Science",
    cgpa: 9.5,
    grade: "O",
    company: "BinarySquad",
    location: "Berhampur, Odisha",
    phone: "+91 9876500002",
    bio: "BSc CS Honours graduate with distinction. Strong foundation in algorithms, AI, and web technologies. Building tools for education.",
    skills: ["Java", "Python", "C++", "SQL", "Web Technology", "AI"],
    linkedinUrl: "https://www.linkedin.com/in/sujitgouda",
    githubUrl: "https://github.com/sujitgouda",
    portfolioUrl: "https://sujitgouda.dev",
    resumeUrl: "https://drive.google.com/file/d/sujit-resume",
    projectName: "Academic Management System",
    projectUrl: "https://academic-mgmt.onrender.com",
    placementInfo: "BinarySquad — Full Stack Developer",
  },

  // ── 2023-2026 Batch (current final year → upcoming alumni) ───────────────
  {
    name: "Sanjana Panda",
    email: "sanjana.panda@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 8.2,
    grade: "A+",
    company: "TCS",
    location: "Berhampur, Odisha",
    phone: "+91 9876500003",
    bio: "Final year BSc CS student specializing in Python and web development. Placed at TCS ION.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/444sanjana",
    githubUrl: "https://github.com/sanjanapda75-cpu",
    portfolioUrl: "https://sanjanaport.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/sanjana-resume",
    projectName: "Employee Management System",
    projectUrl: "https://emplmgmt.onrender.com/",
    placementInfo: "TCS ION Digital Zone, Khalikote College Area, Berhampur",
  },
  {
    name: "Aayusmita Patro",
    email: "aayusmita.patro@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.8,
    grade: "A",
    company: "TCS",
    location: "Berhampur, Odisha",
    phone: "+91 9876500004",
    bio: "BSc CS student with interest in health-tech applications and data management.",
    skills: ["Python", "Flask", "HTML/CSS", "SQL"],
    linkedinUrl: "https://www.linkedin.com/in/aayusmitap95-jpg/",
    githubUrl: "https://github.com/aayusmitap95-jpg",
    portfolioUrl: "https://aayusmitaportfolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/aayusmita-resume",
    projectName: "Health Tracker",
    projectUrl: "https://healthtracker-fb43.onrender.com/",
    placementInfo: "TCS ION Digital Zone, Khalikote College Area, Berhampur",
  },
  {
    name: "Deepti Pradhan",
    email: "deepti.pradhan@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.5,
    grade: "A",
    company: "TCS",
    location: "Berhampur, Odisha",
    phone: "+91 9876500005",
    bio: "BSc CS student passionate about web development and health-tech solutions.",
    skills: ["Python", "Flask", "JavaScript", "SQL"],
    linkedinUrl: "https://www.linkedin.com/in/deepti-p-08274a392",
    githubUrl: "https://github.com/pdeepti596",
    portfolioUrl: "https://dynamic-profiterole-30dbb9.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/deepti-resume",
    projectName: "Health Tracker",
    projectUrl: "https://healthtracker-ddq5.onrender.com/",
    placementInfo: "TCS ION Digital Zone, Khalikote College Area, Berhampur",
  },
  {
    name: "Smaranika Sahu",
    email: "smaranika.sahu@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 8.0,
    grade: "A+",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500006",
    bio: "BSc CS student interested in clinic management systems and backend development.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/smaranikashu",
    githubUrl: "https://github.com/smaranikashu-crypto",
    portfolioUrl: "https://smarni-portfolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/smaranika-resume",
    projectName: "Clinic Management System",
    projectUrl: "https://cl-6raj.onrender.com",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Swastika Behera",
    email: "swastika.behera@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.6,
    grade: "A",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500007",
    bio: "BSc CS student with focus on Python web applications and database management.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/swastika29",
    githubUrl: "https://github.com/swastikabehera76-spec",
    portfolioUrl: "https://swastikaportfolio76.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/swastika-resume",
    projectName: "Health Tracker",
    projectUrl: "https://library-management-project-gaw6.onrender.com",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Bishnu Priya Sahu",
    email: "bishnupriya.sahu@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.9,
    grade: "A",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500008",
    bio: "BSc CS student with experience in railway and ticket management applications.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/mebishnupriya20/",
    githubUrl: "https://github.com/Mebishnupriya20",
    portfolioUrl: "https://bishnuporttfolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/bishnupriya-resume",
    projectName: "Railway Ticket Management",
    projectUrl: "https://raliway.onrender.com/",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Ipsha Biswal",
    email: "ipsha.biswal@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.7,
    grade: "A",
    company: "ION Digital Zone",
    location: "Guwahati, Assam",
    phone: "+91 9876500009",
    bio: "BSc CS student specializing in student management systems and database design.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/ipsha-bwl/",
    githubUrl: "https://github.com/ipshab56-del",
    portfolioUrl: "https://ipshaportfolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/ipsha-resume",
    projectName: "Student Management System",
    projectUrl: "https://sdntmgmt.onrender.com/",
    placementInfo: "ION Digital Zone IDZ Borjhar, Guwahati, Assam",
  },
  {
    name: "Sriman Narayan",
    email: "sriman.narayan@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.2,
    grade: "B+",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500010",
    bio: "BSc CS student with interest in library and information management systems.",
    skills: ["Python", "Flask", "SQL"],
    linkedinUrl: "https://www.linkedin.com/in/sriman-n-09941339b",
    githubUrl: "https://github.com/sriman300",
    portfolioUrl: "https://sriman-portfolio.netlify.app",
    resumeUrl: "https://drive.google.com/file/d/sriman-resume",
    projectName: "Library Management System",
    projectUrl: "https://library-management-project-gaw6.onrender.com",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "P Suman Patro",
    email: "suman.patro@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.8,
    grade: "A",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500011",
    bio: "BSc CS student experienced in rental and property management system development.",
    skills: ["Python", "Flask", "SQL", "Git"],
    linkedinUrl: "https://www.linkedin.com/in/p-suman-patro-16962526a",
    githubUrl: "https://github.com/sumanpatro-SC",
    portfolioUrl: "https://psuman.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/suman-resume",
    projectName: "Rental Management System",
    projectUrl: "https://rental-system-ylwp.onrender.com/",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Sidharth Sahu",
    email: "sidharth.sahu@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.6,
    grade: "A",
    company: "ION Digital Zone",
    location: "Guwahati, Assam",
    phone: "+91 9876500012",
    bio: "BSc CS student focused on employee management systems and enterprise applications.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/sidharthsahu12111/",
    githubUrl: "https://github.com/siddharthsahu1211-ops",
    portfolioUrl: "https://sidharthsahu.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/sidharth-resume",
    projectName: "Employee Management System",
    projectUrl: "https://empmgnt.onrender.com",
    placementInfo: "ION Digital Zone IDZ Borjhar, Guwahati, Assam",
  },
  {
    name: "Smaranika Sahu",
    email: "smaranika2.sahu@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.4,
    grade: "A",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500013",
    bio: "BSc CS student with experience in railway reservation and ticket booking systems.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/mesmaranika20/",
    githubUrl: "https://github.com/mesmaranika20",
    portfolioUrl: "https://smaranikaportfolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/smaranika2-resume",
    projectName: "Train Ticket Reservation",
    projectUrl: "https://railway-2vyj.onrender.com",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Alisha Rani Patro",
    email: "alisha.patro@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.3,
    grade: "B+",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500014",
    bio: "BSc CS student with interest in restaurant and food service management applications.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/mealisha20",
    githubUrl: "https://github.com/mealisha20",
    portfolioUrl: "https://rpalishaportfolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/alisha-resume",
    projectName: "Restaurant Management System",
    projectUrl: "https://restaurant-slkr.onrender.com",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "T Pranati Patro",
    email: "pranati.patro@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.5,
    grade: "A",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500015",
    bio: "BSc CS student focused on restaurant management and hospitality tech solutions.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/mepranatipatro20/",
    githubUrl: "https://github.com/mepranati20",
    portfolioUrl: "https://portfoliopranati.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/pranati-resume",
    projectName: "Restaurant Management System",
    projectUrl: "https://restaurant-30kt.onrender.com",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Nibedita Mahapatra",
    email: "nibedita.mahapatra@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 8.1,
    grade: "A+",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500016",
    bio: "BSc CS student with expertise in hospital and clinic management system development.",
    skills: ["Python", "Flask", "SQL", "JavaScript"],
    linkedinUrl: "https://www.linkedin.com/in/nibeditampa",
    githubUrl: "https://github.com/nibeditampa",
    portfolioUrl: "https://nibedita-portfolio.netlify.app",
    resumeUrl: "https://drive.google.com/file/d/nibedita-resume",
    projectName: "Hospital Management System",
    projectUrl: "https://cms-done12.onrender.com/",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Jagruti Satapathy",
    email: "jagruti.satapathy@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.6,
    grade: "A",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500017",
    bio: "BSc CS student specializing in clinic management systems and healthcare tech.",
    skills: ["Python", "Flask", "SQL", "HTML/CSS"],
    linkedinUrl: "https://www.linkedin.com/in/jagruti-satapathy",
    githubUrl: "https://github.com/jagrutistpy-dot",
    portfolioUrl: "https://jagruti-portfolio.netlify.app",
    resumeUrl: "https://drive.google.com/file/d/jagruti-resume",
    projectName: "Clinic Management System",
    projectUrl: "https://cms-system-8fgv.onrender.com/home",
    placementInfo: "Actively seeking placement opportunities",
  },
  {
    name: "Ipsita Das",
    email: "ipsita.das@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 8.4,
    grade: "A+",
    company: "Anthem Global Technology",
    location: "Bhubaneswar, Odisha",
    phone: "+91 9876500018",
    bio: "BSc CS student placed at Anthem Global Technology. Experienced in academic portal development.",
    skills: ["Python", "Flask", "SQL", "JavaScript"],
    linkedinUrl: "https://www.linkedin.com/in/ipsitadas1510/",
    githubUrl: "https://github.com/IpsitaDas1510",
    portfolioUrl: "https://ipsitafolio.netlify.app/",
    resumeUrl: "https://drive.google.com/file/d/ipsita-resume",
    projectName: "Academic Management Portal",
    projectUrl: "https://amp-i54u.onrender.com/",
    placementInfo: "Anthem Global Technology Service, Chandaka IT Zone, Bhubaneswar",
  },
  {
    name: "P Sneha Reddy",
    email: "sneha.reddy@svm.edu",
    year: "2026",
    major: "Computer Science",
    cgpa: 7.1,
    grade: "B+",
    company: "Seeking Opportunities",
    location: "Berhampur, Odisha",
    phone: "+91 9876500019",
    bio: "BSc CS student with interest in student management and academic systems.",
    skills: ["Python", "Flask", "SQL"],
    linkedinUrl: "https://www.linkedin.com/in/sneha-reddy-svm",
    githubUrl: "https://github.com/snehareddy-svm",
    portfolioUrl: "https://sneha-portfolio.netlify.app",
    resumeUrl: "https://drive.google.com/file/d/sneha-resume",
    projectName: "Student Management System",
    projectUrl: "https://pro1-705u.onrender.com/",
    placementInfo: "Actively seeking placement opportunities",
  },
];

async function main() {
  console.log("🌱 Seeding alumni data (real + upcoming batch)...\n");

  let created = 0;
  let updated = 0;

  for (const alumnus of alumni) {
    const existing = await prisma.user.findUnique({
      where: { email: alumnus.email },
    });

    const data = {
      name: alumnus.name,
      role: Role.ALUMNI,
      groups: ["alumni"],
      isActive: true,
      major: alumnus.major,
      year: alumnus.year,
      bio: alumnus.bio,
      skills: alumnus.skills,
      company: alumnus.company,
      location: alumnus.location,
      phone: alumnus.phone,
      cgpa: alumnus.cgpa,
      grade: alumnus.grade,
      linkedinUrl: alumnus.linkedinUrl,
      githubUrl: alumnus.githubUrl,
      portfolioUrl: alumnus.portfolioUrl,
      resumeUrl: alumnus.resumeUrl,
      projectName: alumnus.projectName,
      projectUrl: alumnus.projectUrl,
      placementInfo: alumnus.placementInfo,
    };

    if (existing) {
      await prisma.user.update({
        where: { email: alumnus.email },
        data,
      });
      updated++;
      console.log(`  ✏️  Updated: ${alumnus.name} (${alumnus.email})`);
    } else {
      await prisma.user.create({
        data: {
          ...data,
          email: alumnus.email,
          authentikId: `seed-${alumnus.email}`,
        },
      });
      created++;
      console.log(`  ✅ Created: ${alumnus.name} (${alumnus.email})`);
    }
  }

  console.log(
    `\n🎉 Seeding complete! Created: ${created}, Updated: ${updated}, Total: ${alumni.length}`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
